- name:
  block:
    - name: "Install package {{ item }}"
      package:
        name: "{{ item }}"
        state: latest
      with_items:
        - htop
        - mc
        - rsync
        - pip
        - python3
        - python3-docker
        - docker-compose
        - net-tools
        - mysql-client-core-8.0
        - python3-pymysql
