---
# tasks file for host-setup

- name: Run docker install
  include_tasks: docker-install.yml

- name: Add users
  include_tasks: user_create.yml

- name: Install some additional packages
  include_tasks: install_packages.yml
