- name: Create users
  block:
    - name: Create users
      user:
        name: "{{ item }}"
        comment: default user
        uid: 1001
        group: admin
      with_items: "{{ users }}"

    - name: Add ssh publish keys
      authorized_key:
        user: "{{ item }}"
        exclusive: yes
        key: "{{ ssh_keys|map(attribute='publish_ssh_key')|join('\n') }}"
      with_items: "{{ users }}"

    - name: Allow admin users to sudo without a password
      lineinfile:
        dest: "/etc/sudoers"
        state: "present"
        regexp: "^%admin"
        line: "%admin ALL=(ALL) NOPASSWD: ALL"
