- name: Run docker compose project
  block:
    - name: Tear down exist project
      docker_compose:
        project_src: "{{ project_dir }}"
        state: absent
      ignore_errors: true

    - name: Create new project
      docker_compose:
        project_src: "{{ project_dir }}"
        env_file: "{{ project_dir }}/.env"
      register: output

    - debug:
        var: output
