name: Run playbook
run-name: Project cooking
on: push
jobs:
  deploy:
    needs: cook
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Cooking project
        uses: dawidd6/action-ansible-playbook@v2
        with:
          # Required, playbook filepath
          playbook: project.yml
          # Optional, directory where playbooks live
          directory: .
          # Optional, SSH private key
          key: ${{secrets.SSH_PRIVATE_KEY}}
          # Optional, encrypted vault password
          vault_password: ${{secrets.VAULT_PASSWORD}}
          # Optional, additional flags to pass to ansible-playbook
          options: |
            --inventory hosts/hosts.yml
